### ISSUE TITLE
Message Prefix Not working

### ISSUE THREAD

**Issue by JakeMcCarron** [ParadauxIO/HiberniaDiscord#6]
Have looked at the code, the prefix is being wiped and then the check for a prefix is being done, when I think it should be the other way round.

In AsyncPlayerChatEventListener:

This:
            messageContent = messageContent.replace(config.getMessagePrefix(), "");
            if (!messageContent.startsWith(config.getMessagePrefix())) return;

Should be:
            if (!messageContent.startsWith(config.getMessagePrefix())) return;
            messageContent = messageContent.replace(config.getMessagePrefix(), "");

**Comment by ParadauxIO** [comment]
Thanks for making me aware, and apologies for the late reply, busy with college work! 

I'll push a patch by the end of the week!

**Comment by ParadauxIO** [comment]
Fixed in the next release!
