### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by pop4959** [ParadauxIO/HiberniaDiscord#8]
The currently linked instructions [here](https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks) are a bit outdated. There is no longer a dedicated "Webhooks" tab; instead "Integrations", where then you can configure the web hooks. I suggest updating or mentioning this expressly on the plugin page to avoid additional confusion when setting up.

**Comment by ParadauxIO** [comment]
I expected they would have been updated by now -- Apologies. I'll have my own wiki page for it tomorrow.

**Comment by ParadauxIO** [comment]
Temporary created: https://github.com/ParadauxIO/HiberniaDiscord/wiki/Creating-a-webhook 
New link will be included in 3.0.2 slated to come out this weekend.
